INSERT INTO equipos (id, nombre, liga, pais) VALUES (1, 'Real Madrid', 'La Liga', 'España');
INSERT INTO equipos (id, nombre, liga, pais) VALUES (2, 'FC Barcelona', 'La Liga', 'España');
INSERT INTO equipos (id, nombre, liga, pais) VALUES (3, 'Manchester United', 'Premier League', 'Inglaterra');
INSERT INTO equipos (id, nombre, liga, pais) VALUES (4, 'Liverpool FC', 'Premier League', 'Inglaterra');
INSERT INTO equipos (id, nombre, liga, pais) VALUES (5, 'Juventus FC', 'Serie A', 'Italia');
INSERT INTO equipos (id, nombre, liga, pais) VALUES (6, 'AC Milan', 'Serie A', 'Italia');
INSERT INTO equipos (id, nombre, liga, pais) VALUES (7, 'Bayern Munich', 'Bundesliga', 'Alemania');
INSERT INTO equipos (id, nombre, liga, pais) VALUES (8, 'Borussia Dortmund', 'Bundesliga', 'Alemania');
INSERT INTO equipos (id, nombre, liga, pais) VALUES (9, 'Paris Saint-Germain', 'Ligue 1', 'Francia');
INSERT INTO equipos (id, nombre, liga, pais) VALUES (10, 'Olympique de Marseille', 'Ligue 1', 'Francia');
INSERT INTO equipos (id, nombre, liga, pais) VALUES (11, 'FC Porto', 'Primeira Liga', 'Portugal');
INSERT INTO equipos (id, nombre, liga, pais) VALUES (12, 'Sporting CP', 'Primeira Liga', 'Portugal');
INSERT INTO equipos (id, nombre, liga, pais) VALUES (13, 'Ajax Amsterdam', 'Eredivisie', 'Países Bajos');
INSERT INTO equipos (id, nombre, liga, pais) VALUES (14, 'Feyenoord', 'Eredivisie', 'Países Bajos');
INSERT INTO equipos (id, nombre, liga, pais) VALUES (15, 'Celtic FC', 'Scottish Premiership', 'Escocia');
INSERT INTO equipos (id, nombre, liga, pais) VALUES (16, 'Rangers FC', 'Scottish Premiership', 'Escocia');
INSERT INTO equipos (id, nombre, liga, pais) VALUES (17, 'Galatasaray SK', 'Süper Lig', 'Turquía');
INSERT INTO equipos (id, nombre, liga, pais) VALUES (18, 'Fenerbahçe SK', 'Süper Lig', 'Turquía');
INSERT INTO equipos (id, nombre, liga, pais) VALUES (19, 'FC Zenit Saint Petersburg', 'Premier League Rusa', 'Rusia');
INSERT INTO equipos (id, nombre, liga, pais) VALUES (20, 'Spartak Moscow', 'Premier League Rusa', 'Rusia');
INSERT INTO equipos (id, nombre, liga, pais) VALUES (21, 'SL Benfica', 'Primeira Liga', 'Portugal');
INSERT INTO equipos (id, nombre, liga, pais) VALUES (22, 'Besiktas JK', 'Süper Lig', 'Turquía');
INSERT INTO equipos (id, nombre, liga, pais) VALUES (23, 'SSC Napoli', 'Serie A', 'Italia');
INSERT INTO equipos (id, nombre, liga, pais) VALUES (24, 'Atlético Madrid', 'La Liga', 'España');